FROM openjdk:11

ADD DriveMain.class DriveMain.class
ADD abc.txt abc.txt
ADD subs.class subs.class
ADD serv_code.class serv_code.class 
ADD PubCode.class PubCode.class
ADD info.class info.class
ENTRYPOINT ["java","DriveMain"]
